version: "2.2"

services:
  eclipse-theia:
    restart: always
    image: theiaide/theia-full
    security_opt:
      - seccomp:unconfined
    init: true
    environment:
      - VIRTUAL_HOST=test.gitpod.domain.com
      - LETSENCRYPT_HOST=test.gitpod.domain.com
    ports:
      - "3000:3000"
    volumes:
      - "./code:/home/project:cached"
    user: "0:0"
